[build]
builder = "NIXPACKS"
[build.nixpacksPlan]
phases = ["install", "start"]

[install]
command = "pip install -r requirements.txt"

[start]
command = "uvicorn main:app --host 0.0.0.0 --port 8000"
